baseURL = "/"
title = "My New Hugo Site"
# デフォルトでは画像がhost名からの相対パスで記載され個別ページで404となるケースがあるため絶対パスとして扱う
canonifyurls = true

# 利用するテーマ
theme = ["docsy"]

# デフォルトの言語設定
defaultContentLanguage = "ja"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      guessSyntax = "true"

# フッターに表示されるcopyrightの設定
[params]
copyright = "Markdown-Hugo-Pages"
prism_syntax_highlighting = true
# ユーザインターフェース（サイドバー、パンくずリスト、検索機能、ロゴ、フッター）に関わる設定
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true
